version: "3"

services:
  server:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: ${MEMORY:-1G}
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./data:/data
