version: "3"

services:
  server:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: ${MAX_MEMORY:-1G}
      MOTD: ${MESSAGE_OF_THE_DAY:-Welcome to the server!}
      VERSION: ${MINECRAFT_VERSION:-LATEST}
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./data:/data
